SEO_CANDIDATE_SEEDS = {
    "SEO Tools": [
        "Ahrefs",
        "Semrush",
        "Moz",
        "Mangools",
        "Serpstat",
        "SE Ranking",
        "Surfer",
        "Frase",
        "Clearscope",
        "Screaming Frog",
        "BrightEdge",
        "Conductor",
        "Lumar",
        "Botify",
        "MarketMuse",
        "Ubersuggest",
        "Rank Math",
        "Yoast",
        "AIOSEO",
        "SEOTesting",
    ],
    "Email Marketing": [
        "Mailchimp",
        "Klaviyo",
        "ConvertKit",
        "ActiveCampaign",
        "Brevo",
        "Campaign Monitor",
        "GetResponse",
        "Drip",
        "Omnisend",
        "Constant Contact",
        "AWeber",
        "MailerLite",
        "Beehiiv",
        "Substack",
        "Customer.io",
        "Iterable",
        "Braze",
        "Sendlane",
        "Moosend",
        "Emma",
    ],
    "CRM": [
        "Salesforce",
        "HubSpot",
        "Pipedrive",
        "Zoho CRM",
        "Freshsales",
        "Copper",
        "Keap",
        "Close",
        "Insightly",
        "Nutshell",
        "Salesflare",
        "Capsule",
        "Zendesk Sell",
        "Less Annoying CRM",
        "SugarCRM",
        "Monday CRM",
        "Attio",
        "Folk",
        "Clay",
        "GoHighLevel",
    ],
    "Project Management": [
        "Asana",
        "Monday",
        "ClickUp",
        "Trello",
        "Notion",
        "Basecamp",
        "Teamwork",
        "Wrike",
        "Jira",
        "Airtable",
        "Smartsheet",
        "Linear",
        "Height",
        "Coda",
        "Todoist",
        "MeisterTask",
        "Hive",
        "ProofHub",
        "Workfront",
        "Shortcut",
    ],
    "Marketing Automation": [
        "Marketo",
        "Pardot",
        "HubSpot Marketing Hub",
        "ActiveCampaign",
        "Customer.io",
        "Iterable",
        "Braze",
        "Klaviyo",
        "Omnisend",
        "Drip",
        "Ortto",
        "Autopilot",
        "GetResponse",
        "Keap",
        "GoHighLevel",
        "SharpSpring",
        "EngageBay",
        "Leadpages",
        "Unbounce",
        "Instapage",
    ],
    "Analytics": [
        "Google Analytics",
        "Mixpanel",
        "Amplitude",
        "Heap",
        "Hotjar",
        "FullStory",
        "PostHog",
        "Plausible",
        "Fathom Analytics",
        "Looker",
        "Tableau",
        "Power BI",
        "Databox",
        "Kissmetrics",
        "Woopra",
        "Segment",
        "RudderStack",
        "Supermetrics",
        "Triple Whale",
        "Northbeam",
    ],
    "Ecommerce": [
        "Shopify",
        "BigCommerce",
        "WooCommerce",
        "Squarespace",
        "Wix",
        "Webflow",
        "Etsy",
        "Amazon",
        "eBay",
        "Faire",
        "Printful",
        "Printify",
        "ShipBob",
        "ShipStation",
        "Gorgias",
        "Yotpo",
        "Recharge",
        "Loop Returns",
        "AfterShip",
        "Klaviyo",
    ],
    "Supplements": [
        "AG1",
        "Ritual",
        "Seed",
        "Bloom Nutrition",
        "Cymbiotika",
        "LMNT",
        "Liquid I.V.",
        "Huel",
        "MyProtein",
        "Goli",
        "Care/of",
        "Thorne",
        "Momentous",
        "Transparent Labs",
        "Onnit",
        "Athletic Greens",
        "Moon Juice",
        "Olly",
        "Hum Nutrition",
        "Nature Made",
    ],
    "Fitness": [
        "Peloton",
        "Strava",
        "WHOOP",
        "Oura",
        "Fitbit",
        "Tonal",
        "Mirror",
        "Noom",
        "MyFitnessPal",
        "Alo Moves",
        "Nike Training Club",
        "Gymshark",
        "Lululemon Studio",
        "F45",
        "CrossFit",
        "Centr",
        "Future",
        "Tempo",
        "Hydrow",
        "Zwift",
    ],
    "Productivity": [
        "Notion",
        "Evernote",
        "Todoist",
        "Things",
        "Calendly",
        "Motion",
        "Reclaim",
        "Sunsama",
        "Akiflow",
        "Superhuman",
        "Grammarly",
        "Dropbox",
        "Box",
        "Google Workspace",
        "Microsoft 365",
        "Slack",
        "Zoom",
        "Loom",
        "Miro",
        "Lucidchart",
    ],
    "AI Tools": [
        "ChatGPT",
        "Claude",
        "Perplexity",
        "Jasper",
        "Copy.ai",
        "Writer",
        "Typeface",
        "Runway",
        "Synthesia",
        "Descript",
        "Midjourney",
        "Canva",
        "Gamma",
        "Tome",
        "Zapier",
        "Make",
        "Replit",
        "Cursor",
        "Fireflies.ai",
        "Otter.ai",
    ],
    "Grooming": [
        "Manscaped",
        "Dollar Shave Club",
        "Harry's",
        "Hims",
        "Keeps",
        "Dr. Squatch",
        "Bevel",
        "Gillette",
        "Braun",
        "Philips Norelco",
        "The Art of Shaving",
        "Cremo",
        "Native",
        "Old Spice",
        "Every Man Jack",
        "Method Men",
        "Supply",
        "Hawthorne",
        "Lumin",
        "Geologie",
    ],
    "Beauty": [
        "Sephora",
        "Ulta Beauty",
        "Glossier",
        "Curology",
        "Fenty Beauty",
        "Rare Beauty",
        "Kylie Cosmetics",
        "The Ordinary",
        "Drunk Elephant",
        "Tatcha",
        "ILIA",
        "Saie",
        "Merit",
        "Tower 28",
        "Supergoop",
        "Paula's Choice",
        "CeraVe",
        "La Roche-Posay",
        "Function of Beauty",
        "Prose",
    ],
    "Fashion": [
        "Nike",
        "Adidas",
        "Gymshark",
        "Lululemon",
        "Vuori",
        "Skims",
        "Alo Yoga",
        "Allbirds",
        "Warby Parker",
        "Quince",
        "Bombas",
        "Everlane",
        "Rothy's",
        "MeUndies",
        "Cuts Clothing",
        "True Classic",
        "On Running",
        "Hoka",
        "Outdoor Voices",
        "Reformation",
    ],
}


def get_seed_categories():
    return list(SEO_CANDIDATE_SEEDS.keys())


def get_seed_brands_for_categories(categories):
    selected = []
    seen = set()
    for category in categories:
        for brand_name in SEO_CANDIDATE_SEEDS.get(category, []):
            key = brand_name.strip().lower()
            if not key or key in seen:
                continue
            selected.append({"brand_name": brand_name, "category": category})
            seen.add(key)
    return selected
